services:
  - type: web
    name: dang-calendar
    runtime: node
    buildCommand: ./render-build.sh
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
