services:
  - type: web
    name: dang-calendar
    runtime: node
    buildCommand: bash ./render-build.sh
    startCommand: npm start
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/.cache/puppeteer
