services:
  - type: web
    name: dang-calendar
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/.cache
